import { ThemeRegistry } from "@/libs";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="web">
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
