import { ThemeRegistry } from "@/libs";
import { ToastContainer } from "react-toastify";

import "react-toastify/dist/ReactToastify.min.css";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body id="web">
        <ThemeRegistry>{children}</ThemeRegistry>

        <ToastContainer position="bottom-right" draggable={false} limit={3} />
      </body>
    </html>
  );
};

export default RootLayout;
